### ISSUE TITLE
ROSplane documentation

### ISSUE THREAD

**Issue by bsutherland333** [rosflight/rosplane#19]
We need to have full documentation so that a new user could pick up the software, and then implement it, and then modify the code to their needs.

**Comment by iandareid** [comment]
A first draft of the successive loop closure overview is completed. @bsutherland333, @JMoore5353 , could you look over the page and give me your thoughts? More diagrams for the page are forthcoming.

**Comment by iandareid** [comment]
There is now a draft pull request where you can leave notes.

**Comment by iandareid** [comment]
Drafts for each of the major parts of the controller are posted.

**Comment by iandareid** [comment]
The controller documentation is in an MVP state.

**Comment by JMoore5353** [comment]
- [ ] Add link from GH README to website
- [ ] Add GIFS GH README
- [ ] Tuning Guide on User Guide
- [ ] Add a figure to the path follower about vector fields
- [ ] Add information to path manager talking about waypoint transition criteria.
